// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

/**
 * Protobuf type {@code CreatePartitionRequest}
 */
public final class CreatePartitionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreatePartitionRequest)
    CreatePartitionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreatePartitionRequest.newBuilder() to construct.
  private CreatePartitionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreatePartitionRequest() {
    topic_ = "";
    topicType_ = "";
    topicMode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreatePartitionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.catmq.protocol.service.Service.internal_static_CreatePartitionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.catmq.protocol.service.Service.internal_static_CreatePartitionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.catmq.protocol.service.CreatePartitionRequest.class, org.catmq.protocol.service.CreatePartitionRequest.Builder.class);
  }

  public static final int TOPIC_FIELD_NUMBER = 1;
  private volatile java.lang.Object topic_;
  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITIONINDEX_FIELD_NUMBER = 2;
  private int partitionIndex_;
  /**
   * <code>int32 partitionIndex = 2;</code>
   * @return The partitionIndex.
   */
  @java.lang.Override
  public int getPartitionIndex() {
    return partitionIndex_;
  }

  public static final int TOPICTYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object topicType_;
  /**
   * <code>string topicType = 3;</code>
   * @return The topicType.
   */
  @java.lang.Override
  public java.lang.String getTopicType() {
    java.lang.Object ref = topicType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topicType_ = s;
      return s;
    }
  }
  /**
   * <code>string topicType = 3;</code>
   * @return The bytes for topicType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicTypeBytes() {
    java.lang.Object ref = topicType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topicType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPICMODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object topicMode_;
  /**
   * <code>string topicMode = 4;</code>
   * @return The topicMode.
   */
  @java.lang.Override
  public java.lang.String getTopicMode() {
    java.lang.Object ref = topicMode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topicMode_ = s;
      return s;
    }
  }
  /**
   * <code>string topicMode = 4;</code>
   * @return The bytes for topicMode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicModeBytes() {
    java.lang.Object ref = topicMode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topicMode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
    }
    if (partitionIndex_ != 0) {
      output.writeInt32(2, partitionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topicType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicMode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, topicMode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
    }
    if (partitionIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, partitionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topicType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicMode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, topicMode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.catmq.protocol.service.CreatePartitionRequest)) {
      return super.equals(obj);
    }
    org.catmq.protocol.service.CreatePartitionRequest other = (org.catmq.protocol.service.CreatePartitionRequest) obj;

    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (getPartitionIndex()
        != other.getPartitionIndex()) return false;
    if (!getTopicType()
        .equals(other.getTopicType())) return false;
    if (!getTopicMode()
        .equals(other.getTopicMode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + PARTITIONINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getPartitionIndex();
    hash = (37 * hash) + TOPICTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTopicType().hashCode();
    hash = (37 * hash) + TOPICMODE_FIELD_NUMBER;
    hash = (53 * hash) + getTopicMode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.service.CreatePartitionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.catmq.protocol.service.CreatePartitionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreatePartitionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreatePartitionRequest)
      org.catmq.protocol.service.CreatePartitionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.catmq.protocol.service.Service.internal_static_CreatePartitionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.catmq.protocol.service.Service.internal_static_CreatePartitionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.catmq.protocol.service.CreatePartitionRequest.class, org.catmq.protocol.service.CreatePartitionRequest.Builder.class);
    }

    // Construct using org.catmq.protocol.service.CreatePartitionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      topic_ = "";

      partitionIndex_ = 0;

      topicType_ = "";

      topicMode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.catmq.protocol.service.Service.internal_static_CreatePartitionRequest_descriptor;
    }

    @java.lang.Override
    public org.catmq.protocol.service.CreatePartitionRequest getDefaultInstanceForType() {
      return org.catmq.protocol.service.CreatePartitionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.catmq.protocol.service.CreatePartitionRequest build() {
      org.catmq.protocol.service.CreatePartitionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.catmq.protocol.service.CreatePartitionRequest buildPartial() {
      org.catmq.protocol.service.CreatePartitionRequest result = new org.catmq.protocol.service.CreatePartitionRequest(this);
      result.topic_ = topic_;
      result.partitionIndex_ = partitionIndex_;
      result.topicType_ = topicType_;
      result.topicMode_ = topicMode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.catmq.protocol.service.CreatePartitionRequest) {
        return mergeFrom((org.catmq.protocol.service.CreatePartitionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.catmq.protocol.service.CreatePartitionRequest other) {
      if (other == org.catmq.protocol.service.CreatePartitionRequest.getDefaultInstance()) return this;
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (other.getPartitionIndex() != 0) {
        setPartitionIndex(other.getPartitionIndex());
      }
      if (!other.getTopicType().isEmpty()) {
        topicType_ = other.topicType_;
        onChanged();
      }
      if (!other.getTopicMode().isEmpty()) {
        topicMode_ = other.topicMode_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              topic_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              partitionIndex_ = input.readInt32();

              break;
            } // case 16
            case 26: {
              topicType_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              topicMode_ = input.readStringRequireUtf8();

              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 1;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private int partitionIndex_ ;
    /**
     * <code>int32 partitionIndex = 2;</code>
     * @return The partitionIndex.
     */
    @java.lang.Override
    public int getPartitionIndex() {
      return partitionIndex_;
    }
    /**
     * <code>int32 partitionIndex = 2;</code>
     * @param value The partitionIndex to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionIndex(int value) {
      
      partitionIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 partitionIndex = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartitionIndex() {
      
      partitionIndex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object topicType_ = "";
    /**
     * <code>string topicType = 3;</code>
     * @return The topicType.
     */
    public java.lang.String getTopicType() {
      java.lang.Object ref = topicType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topicType = 3;</code>
     * @return The bytes for topicType.
     */
    public com.google.protobuf.ByteString
        getTopicTypeBytes() {
      java.lang.Object ref = topicType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topicType = 3;</code>
     * @param value The topicType to set.
     * @return This builder for chaining.
     */
    public Builder setTopicType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topicType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topicType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicType() {
      
      topicType_ = getDefaultInstance().getTopicType();
      onChanged();
      return this;
    }
    /**
     * <code>string topicType = 3;</code>
     * @param value The bytes for topicType to set.
     * @return This builder for chaining.
     */
    public Builder setTopicTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topicType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topicMode_ = "";
    /**
     * <code>string topicMode = 4;</code>
     * @return The topicMode.
     */
    public java.lang.String getTopicMode() {
      java.lang.Object ref = topicMode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicMode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topicMode = 4;</code>
     * @return The bytes for topicMode.
     */
    public com.google.protobuf.ByteString
        getTopicModeBytes() {
      java.lang.Object ref = topicMode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicMode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topicMode = 4;</code>
     * @param value The topicMode to set.
     * @return This builder for chaining.
     */
    public Builder setTopicMode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topicMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topicMode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicMode() {
      
      topicMode_ = getDefaultInstance().getTopicMode();
      onChanged();
      return this;
    }
    /**
     * <code>string topicMode = 4;</code>
     * @param value The bytes for topicMode to set.
     * @return This builder for chaining.
     */
    public Builder setTopicModeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topicMode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreatePartitionRequest)
  }

  // @@protoc_insertion_point(class_scope:CreatePartitionRequest)
  private static final org.catmq.protocol.service.CreatePartitionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.catmq.protocol.service.CreatePartitionRequest();
  }

  public static org.catmq.protocol.service.CreatePartitionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatePartitionRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreatePartitionRequest>() {
    @java.lang.Override
    public CreatePartitionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreatePartitionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreatePartitionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.catmq.protocol.service.CreatePartitionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

