// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface CreatePartitionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatePartitionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>int32 partitionIndex = 2;</code>
   * @return The partitionIndex.
   */
  int getPartitionIndex();

  /**
   * <code>string topicType = 3;</code>
   * @return The topicType.
   */
  java.lang.String getTopicType();
  /**
   * <code>string topicType = 3;</code>
   * @return The bytes for topicType.
   */
  com.google.protobuf.ByteString
      getTopicTypeBytes();

  /**
   * <code>string topicMode = 4;</code>
   * @return The topicMode.
   */
  java.lang.String getTopicMode();
  /**
   * <code>string topicMode = 4;</code>
   * @return The bytes for topicMode.
   */
  com.google.protobuf.ByteString
      getTopicModeBytes();
}
