// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface GetMessageFromStorerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetMessageFromStorerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 segment_id = 2;</code>
   * @return The segmentId.
   */
  long getSegmentId();

  /**
   * <code>int64 entry_id = 3;</code>
   * @return The entryId.
   */
  long getEntryId();
}
