// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface SendMessage2BrokerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage2BrokerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .OriginMessage message = 1;</code>
   */
  java.util.List<org.catmq.protocol.definition.OriginMessage>
      getMessageList();
  /**
   * <code>repeated .OriginMessage message = 1;</code>
   */
  org.catmq.protocol.definition.OriginMessage getMessage(int index);
  /**
   * <code>repeated .OriginMessage message = 1;</code>
   */
  int getMessageCount();
  /**
   * <code>repeated .OriginMessage message = 1;</code>
   */
  java.util.List<? extends org.catmq.protocol.definition.OriginMessageOrBuilder>
      getMessageOrBuilderList();
  /**
   * <code>repeated .OriginMessage message = 1;</code>
   */
  org.catmq.protocol.definition.OriginMessageOrBuilder getMessageOrBuilder(
      int index);

  /**
   * <code>int64 producerId = 2;</code>
   * @return The producerId.
   */
  long getProducerId();

  /**
   * <code>string topic = 3;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 3;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
