// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface SendMessage2BrokerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage2BrokerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 segmentId = 1;</code>
   * @return The segmentId.
   */
  long getSegmentId();

  /**
   * <code>int64 firstEntryId = 2;</code>
   * @return The firstEntryId.
   */
  long getFirstEntryId();

  /**
   * <code>int64 lastEntryId = 3;</code>
   * @return The lastEntryId.
   */
  long getLastEntryId();

  /**
   * <code>bool ack = 4;</code>
   * @return The ack.
   */
  boolean getAck();

  /**
   * <code>string res = 5;</code>
   * @return The res.
   */
  java.lang.String getRes();
  /**
   * <code>string res = 5;</code>
   * @return The bytes for res.
   */
  com.google.protobuf.ByteString
      getResBytes();

  /**
   * <code>.Status status = 6;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.Status status = 6;</code>
   * @return The status.
   */
  org.catmq.protocol.definition.Status getStatus();
  /**
   * <code>.Status status = 6;</code>
   */
  org.catmq.protocol.definition.StatusOrBuilder getStatusOrBuilder();
}
