// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface SendMessage2StorerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage2StorerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .NumberedMessage message = 1;</code>
   */
  java.util.List<org.catmq.protocol.definition.NumberedMessage>
      getMessageList();
  /**
   * <code>repeated .NumberedMessage message = 1;</code>
   */
  org.catmq.protocol.definition.NumberedMessage getMessage(int index);
  /**
   * <code>repeated .NumberedMessage message = 1;</code>
   */
  int getMessageCount();
  /**
   * <code>repeated .NumberedMessage message = 1;</code>
   */
  java.util.List<? extends org.catmq.protocol.definition.NumberedMessageOrBuilder>
      getMessageOrBuilderList();
  /**
   * <code>repeated .NumberedMessage message = 1;</code>
   */
  org.catmq.protocol.definition.NumberedMessageOrBuilder getMessageOrBuilder(
      int index);

  /**
   * <code>string mode = 2;</code>
   * @return The mode.
   */
  java.lang.String getMode();
  /**
   * <code>string mode = 2;</code>
   * @return The bytes for mode.
   */
  com.google.protobuf.ByteString
      getModeBytes();
}
