// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

public final class Definition {
  private Definition() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Checksum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Checksum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KvPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KvPair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OriginMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OriginMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NumberedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NumberedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020definition.proto\032\037google/protobuf/time" +
      "stamp.proto\032\036google/protobuf/duration.pr" +
      "oto\"5\n\010Checksum\022\033\n\004type\030\001 \001(\0162\r.Checksum" +
      "Type\022\014\n\004body\030\002 \001(\t\"\331\006\n\020SystemProperties\022" +
      "\020\n\003tag\030\001 \001(\tH\000\210\001\001\022\014\n\004keys\030\002 \003(\t\022\022\n\nmessa" +
      "ge_id\030\003 \001(\t\022\036\n\013body_digest\030\004 \001(\0132\t.Check" +
      "sum\022 \n\rbody_encoding\030\005 \001(\0162\t.Encoding\0222\n" +
      "\016born_timestamp\030\007 \001(\0132\032.google.protobuf." +
      "Timestamp\022\021\n\tborn_host\030\010 \001(\t\0228\n\017store_ti" +
      "mestamp\030\t \001(\0132\032.google.protobuf.Timestam" +
      "pH\001\210\001\001\022\022\n\nstore_host\030\n \001(\t\022;\n\022delivery_t" +
      "imestamp\030\013 \001(\0132\032.google.protobuf.Timesta" +
      "mpH\002\210\001\001\022\033\n\016receipt_handle\030\014 \001(\tH\003\210\001\001\022\020\n\010" +
      "queue_id\030\r \001(\005\022\031\n\014queue_offset\030\016 \001(\003H\004\210\001" +
      "\001\022:\n\022invisible_duration\030\017 \001(\0132\031.google.p" +
      "rotobuf.DurationH\005\210\001\001\022\035\n\020delivery_attemp" +
      "t\030\020 \001(\005H\006\210\001\001\022\032\n\rmessage_group\030\021 \001(\tH\007\210\001\001" +
      "\022\032\n\rtrace_context\030\022 \001(\tH\010\210\001\001\022N\n&orphaned" +
      "_transaction_recovery_duration\030\023 \001(\0132\031.g" +
      "oogle.protobuf.DurationH\t\210\001\001B\006\n\004_tagB\022\n\020" +
      "_store_timestampB\025\n\023_delivery_timestampB" +
      "\021\n\017_receipt_handleB\017\n\r_queue_offsetB\025\n\023_" +
      "invisible_durationB\023\n\021_delivery_attemptB" +
      "\020\n\016_message_groupB\020\n\016_trace_contextB)\n\'_" +
      "orphaned_transaction_recovery_duration\"$" +
      "\n\006KvPair\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\".\n\006" +
      "Status\022\023\n\004code\030\001 \001(\0162\005.Code\022\017\n\007message\030\002" +
      " \001(\t\"1\n\rOriginMessage\022\022\n\nexpireTime\030\001 \001(" +
      "\003\022\014\n\004body\030\002 \001(\014\"C\n\017NumberedMessage\022\021\n\tse" +
      "gmentId\030\001 \001(\003\022\017\n\007entryId\030\002 \001(\003\022\014\n\004body\030\003" +
      " \001(\014*W\n\nPermission\022\032\n\026PERMISSION_UNSPECI" +
      "FIED\020\000\022\010\n\004NONE\020\001\022\010\n\004READ\020\002\022\t\n\005WRITE\020\003\022\016\n" +
      "\nREAD_WRITE\020\004*\"\n\013ProcessMode\022\010\n\004SYNC\020\000\022\t" +
      "\n\005ASYNC\020\001*[\n\010Encoding\022\030\n\024ENCODING_UNSPEC" +
      "IFIED\020\000\022\014\n\010IDENTITY\020\001\022\010\n\004GZIP\020\002\022\007\n\003LZ4\020\003" +
      "\022\010\n\004ZSTD\020\004\022\n\n\006SNAPPY\020\005*I\n\014ChecksumType\022\033" +
      "\n\027DIGEST_TYPE_UNSPECIFIED\020\000\022\t\n\005CRC32\020\001\022\007" +
      "\n\003MD5\020\002\022\010\n\004SHA1\020\003*\342\t\n\004Code\022\024\n\020CODE_UNSPE" +
      "CIFIED\020\000\022\010\n\002OK\020\240\234\001\022\026\n\020MULTIPLE_RESULTS\020\260" +
      "\352\001\022\021\n\013BAD_REQUEST\020\300\270\002\022\032\n\024ILLEGAL_ACCESS_" +
      "POINT\020\301\270\002\022\023\n\rILLEGAL_TOPIC\020\302\270\002\022\034\n\026ILLEGA" +
      "L_CONSUMER_GROUP\020\303\270\002\022\031\n\023ILLEGAL_MESSAGE_" +
      "TAG\020\304\270\002\022\031\n\023ILLEGAL_MESSAGE_KEY\020\305\270\002\022\033\n\025IL" +
      "LEGAL_MESSAGE_GROUP\020\306\270\002\022\"\n\034ILLEGAL_MESSA" +
      "GE_PROPERTY_KEY\020\307\270\002\022\034\n\026INVALID_TRANSACTI" +
      "ON_ID\020\310\270\002\022\030\n\022ILLEGAL_MESSAGE_ID\020\311\270\002\022\037\n\031I" +
      "LLEGAL_FILTER_EXPRESSION\020\312\270\002\022\034\n\026ILLEGAL_" +
      "INVISIBLE_TIME\020\313\270\002\022\033\n\025ILLEGAL_DELIVERY_T" +
      "IME\020\314\270\002\022\034\n\026INVALID_RECEIPT_HANDLE\020\315\270\002\022)\n" +
      "#MESSAGE_PROPERTY_CONFLICT_WITH_TYPE\020\316\270\002" +
      "\022\036\n\030UNRECOGNIZED_CLIENT_TYPE\020\317\270\002\022\027\n\021MESS" +
      "AGE_CORRUPTED\020\320\270\002\022\030\n\022CLIENT_ID_REQUIRED\020" +
      "\321\270\002\022\022\n\014UNAUTHORIZED\020\244\271\002\022\026\n\020PAYMENT_REQUI" +
      "RED\020\210\272\002\022\017\n\tFORBIDDEN\020\354\272\002\022\017\n\tNOT_FOUND\020\320\273" +
      "\002\022\027\n\021MESSAGE_NOT_FOUND\020\321\273\002\022\025\n\017TOPIC_NOT_" +
      "FOUND\020\322\273\002\022\036\n\030CONSUMER_GROUP_NOT_FOUND\020\323\273" +
      "\002\022\025\n\017REQUEST_TIMEOUT\020\340\276\002\022\027\n\021PAYLOAD_TOO_" +
      "LARGE\020\324\302\002\022\034\n\026MESSAGE_BODY_TOO_LARGE\020\325\302\002\022" +
      "\031\n\023PRECONDITION_FAILED\020\260\316\002\022\027\n\021TOO_MANY_R" +
      "EQUESTS\020\224\317\002\022%\n\037REQUEST_HEADER_FIELDS_TOO" +
      "_LARGE\020\334\320\002\022\"\n\034MESSAGE_PROPERTIES_TOO_LAR" +
      "GE\020\335\320\002\022\024\n\016INTERNAL_ERROR\020\320\206\003\022\033\n\025INTERNAL" +
      "_SERVER_ERROR\020\321\206\003\022\026\n\020HA_NOT_AVAILABLE\020\322\206" +
      "\003\022\025\n\017NOT_IMPLEMENTED\020\264\207\003\022\023\n\rPROXY_TIMEOU" +
      "T\020\340\211\003\022 \n\032MASTER_PERSISTENCE_TIMEOUT\020\341\211\003\022" +
      "\037\n\031SLAVE_PERSISTENCE_TIMEOUT\020\342\211\003\022\021\n\013UNSU" +
      "PPORTED\020\304\212\003\022\031\n\023VERSION_UNSUPPORTED\020\305\212\003\022%" +
      "\n\037VERIFY_FIFO_MESSAGE_UNSUPPORTED\020\306\212\003\022\037\n" +
      "\031FAILED_TO_CONSUME_MESSAGE\020\340\324\003B*\n\035org.ca" +
      "tmq.protocol.definitionP\001\210\001\001\240\001\001\330\001\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_Checksum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Checksum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Checksum_descriptor,
        new java.lang.String[] { "Type", "Body", });
    internal_static_SystemProperties_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SystemProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemProperties_descriptor,
        new java.lang.String[] { "Tag", "Keys", "MessageId", "BodyDigest", "BodyEncoding", "BornTimestamp", "BornHost", "StoreTimestamp", "StoreHost", "DeliveryTimestamp", "ReceiptHandle", "QueueId", "QueueOffset", "InvisibleDuration", "DeliveryAttempt", "MessageGroup", "TraceContext", "OrphanedTransactionRecoveryDuration", "Tag", "StoreTimestamp", "DeliveryTimestamp", "ReceiptHandle", "QueueOffset", "InvisibleDuration", "DeliveryAttempt", "MessageGroup", "TraceContext", "OrphanedTransactionRecoveryDuration", });
    internal_static_KvPair_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_KvPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KvPair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Status_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_OriginMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OriginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OriginMessage_descriptor,
        new java.lang.String[] { "ExpireTime", "Body", });
    internal_static_NumberedMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_NumberedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NumberedMessage_descriptor,
        new java.lang.String[] { "SegmentId", "EntryId", "Body", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
