// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

public interface NumberedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NumberedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 segmentId = 1;</code>
   * @return The segmentId.
   */
  long getSegmentId();

  /**
   * <code>int64 entryId = 2;</code>
   * @return The entryId.
   */
  long getEntryId();

  /**
   * <code>bytes body = 3;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
