// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

/**
 * Protobuf type {@code NumberedMessage}
 */
public final class NumberedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NumberedMessage)
    NumberedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NumberedMessage.newBuilder() to construct.
  private NumberedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NumberedMessage() {
    body_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NumberedMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.catmq.protocol.definition.Definition.internal_static_NumberedMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.catmq.protocol.definition.Definition.internal_static_NumberedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.catmq.protocol.definition.NumberedMessage.class, org.catmq.protocol.definition.NumberedMessage.Builder.class);
  }

  public static final int SEGMENTID_FIELD_NUMBER = 1;
  private long segmentId_;
  /**
   * <code>int64 segmentId = 1;</code>
   * @return The segmentId.
   */
  @java.lang.Override
  public long getSegmentId() {
    return segmentId_;
  }

  public static final int ENTRYID_FIELD_NUMBER = 2;
  private long entryId_;
  /**
   * <code>int64 entryId = 2;</code>
   * @return The entryId.
   */
  @java.lang.Override
  public long getEntryId() {
    return entryId_;
  }

  public static final int BODY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString body_;
  /**
   * <code>bytes body = 3;</code>
   * @return The body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (segmentId_ != 0L) {
      output.writeInt64(1, segmentId_);
    }
    if (entryId_ != 0L) {
      output.writeInt64(2, entryId_);
    }
    if (!body_.isEmpty()) {
      output.writeBytes(3, body_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (segmentId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, segmentId_);
    }
    if (entryId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, entryId_);
    }
    if (!body_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, body_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.catmq.protocol.definition.NumberedMessage)) {
      return super.equals(obj);
    }
    org.catmq.protocol.definition.NumberedMessage other = (org.catmq.protocol.definition.NumberedMessage) obj;

    if (getSegmentId()
        != other.getSegmentId()) return false;
    if (getEntryId()
        != other.getEntryId()) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEGMENTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSegmentId());
    hash = (37 * hash) + ENTRYID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntryId());
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.definition.NumberedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.catmq.protocol.definition.NumberedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NumberedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NumberedMessage)
      org.catmq.protocol.definition.NumberedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.catmq.protocol.definition.Definition.internal_static_NumberedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.catmq.protocol.definition.Definition.internal_static_NumberedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.catmq.protocol.definition.NumberedMessage.class, org.catmq.protocol.definition.NumberedMessage.Builder.class);
    }

    // Construct using org.catmq.protocol.definition.NumberedMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      segmentId_ = 0L;

      entryId_ = 0L;

      body_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.catmq.protocol.definition.Definition.internal_static_NumberedMessage_descriptor;
    }

    @java.lang.Override
    public org.catmq.protocol.definition.NumberedMessage getDefaultInstanceForType() {
      return org.catmq.protocol.definition.NumberedMessage.getDefaultInstance();
    }

    @java.lang.Override
    public org.catmq.protocol.definition.NumberedMessage build() {
      org.catmq.protocol.definition.NumberedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.catmq.protocol.definition.NumberedMessage buildPartial() {
      org.catmq.protocol.definition.NumberedMessage result = new org.catmq.protocol.definition.NumberedMessage(this);
      result.segmentId_ = segmentId_;
      result.entryId_ = entryId_;
      result.body_ = body_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.catmq.protocol.definition.NumberedMessage) {
        return mergeFrom((org.catmq.protocol.definition.NumberedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.catmq.protocol.definition.NumberedMessage other) {
      if (other == org.catmq.protocol.definition.NumberedMessage.getDefaultInstance()) return this;
      if (other.getSegmentId() != 0L) {
        setSegmentId(other.getSegmentId());
      }
      if (other.getEntryId() != 0L) {
        setEntryId(other.getEntryId());
      }
      if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
        setBody(other.getBody());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              segmentId_ = input.readInt64();

              break;
            } // case 8
            case 16: {
              entryId_ = input.readInt64();

              break;
            } // case 16
            case 26: {
              body_ = input.readBytes();

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long segmentId_ ;
    /**
     * <code>int64 segmentId = 1;</code>
     * @return The segmentId.
     */
    @java.lang.Override
    public long getSegmentId() {
      return segmentId_;
    }
    /**
     * <code>int64 segmentId = 1;</code>
     * @param value The segmentId to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentId(long value) {
      
      segmentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 segmentId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegmentId() {
      
      segmentId_ = 0L;
      onChanged();
      return this;
    }

    private long entryId_ ;
    /**
     * <code>int64 entryId = 2;</code>
     * @return The entryId.
     */
    @java.lang.Override
    public long getEntryId() {
      return entryId_;
    }
    /**
     * <code>int64 entryId = 2;</code>
     * @param value The entryId to set.
     * @return This builder for chaining.
     */
    public Builder setEntryId(long value) {
      
      entryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 entryId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryId() {
      
      entryId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes body = 3;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>bytes body = 3;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes body = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NumberedMessage)
  }

  // @@protoc_insertion_point(class_scope:NumberedMessage)
  private static final org.catmq.protocol.definition.NumberedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.catmq.protocol.definition.NumberedMessage();
  }

  public static org.catmq.protocol.definition.NumberedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NumberedMessage>
      PARSER = new com.google.protobuf.AbstractParser<NumberedMessage>() {
    @java.lang.Override
    public NumberedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NumberedMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NumberedMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.catmq.protocol.definition.NumberedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

