// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

public interface OriginMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OriginMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 expireTime = 1;</code>
   * @return The expireTime.
   */
  long getExpireTime();

  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
