// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

/**
 * Protobuf enum {@code ProcessMode}
 */
public enum ProcessMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SYNC = 0;</code>
   */
  SYNC(0),
  /**
   * <code>ASYNC = 1;</code>
   */
  ASYNC(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SYNC = 0;</code>
   */
  public static final int SYNC_VALUE = 0;
  /**
   * <code>ASYNC = 1;</code>
   */
  public static final int ASYNC_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProcessMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProcessMode forNumber(int value) {
    switch (value) {
      case 0: return SYNC;
      case 1: return ASYNC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProcessMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProcessMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProcessMode>() {
          public ProcessMode findValueByNumber(int number) {
            return ProcessMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.catmq.protocol.definition.Definition.getDescriptor().getEnumTypes().get(1);
  }

  private static final ProcessMode[] VALUES = values();

  public static ProcessMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProcessMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ProcessMode)
}

